name = "web"
compatibility_date = "2024-03-29"
compatibility_flags = ["nodejs_compat"]

[[vectorize]]
binding = "VECTORIZE_INDEX" 
index_name = "anycontext-idx"

[[d1_databases]]
binding = "DATABASE"
database_name = "dev-d1-anycontext"

[vars]
GOOGLE_CLIENT_ID="-"
GOOGLE_CLIENT_SECRET="-"
NEXTAUTH_SECRET="sec"
NEXTAUTH_URL="http://localhost:3000"
BACKEND_SECURITY_KEY="XP1FNh+rTYghq2TmrFbMLCCBy+eBAvi8iuoMuV9zDUc="
