name = "dev-supermemory"
compatibility_date = "2024-03-29"
compatibility_flags = [ "nodejs_compat" ]
pages_build_output_dir = ".vercel/output/static"


kv_namespaces = [
	{ binding = "CANVAS_SNAPS", id = "6df98c892b3744ccb0c631d9f60d6697" },
	{ binding = "RECOMMENDATIONS", id = "83bc7055226c4657948141c2ff9a5425" }
]

env.production.kv_namespaces = [
	{ binding = "CANVAS_SNAPS", id = "6df98c892b3744ccb0c631d9f60d6697" },
	{ binding = "RECOMMENDATIONS", id = "83bc7055226c4657948141c2ff9a5425" }
]

[ai]
binding = "AI"

[placement]
mode = "smart"

[[r2_buckets]]
binding = "STORAGE"
bucket_name = "dev-r2-anycontext"

[[d1_databases]]
binding = "DATABASE"
database_name = "supermemlocal"
database_id = "0f93c990-72fb-489c-8563-57a7bb18dc43"


[[env.production.d1_databases]]
binding = "DATABASE"
database_name = "staging-d1-supermemory"
database_id = "40a3bb06-82bd-42f1-aef4-fde04f3635c5"

[env.preview.ai]
binding = "AI"

[[env.preview.d1_databases]]
binding = "DATABASE"
database_name = "dev-d1-anycontext"
database_id = "fc562605-157a-4f60-b439-2a24ffed5b4c"

[env.production.ai]
binding = "AI"