name = "supermemory"
compatibility_date = "2024-03-29"
compatibility_flags = [ "nodejs_compat" ]
pages_build_output_dir = ".vercel/output/static"


kv_namespaces = [
	{ binding = "CANVAS_SNAPS", id = "24c7048fa9064e7787dd58760b21dc8d" },
	{ binding = "RECOMMENDATIONS", id = "abfd16f09b0b4300908115a5a177429e" }
]

env.production.kv_namespaces = [
	{ binding = "CANVAS_SNAPS", id = "24c7048fa9064e7787dd58760b21dc8d" },
	{ binding = "RECOMMENDATIONS", id = "abfd16f09b0b4300908115a5a177429e" }
]

[ai]
binding = "AI"

[placement]
mode = "smart"

[[r2_buckets]]
binding = "STORAGE"
bucket_name = "supermemory-r2"

[[d1_databases]]
binding = "DATABASE"
database_name = "supermemory-db-preview"
database_id = "b09e126c-8179-4927-876a-6a03ee94334b"


[[env.production.d1_databases]]
binding = "DATABASE"
database_name = "supermemory-db-prod"
database_id = "0dea4084-3629-4aea-938c-da478a32f5cd"

[env.preview.ai]
binding = "AI"

[[env.preview.d1_databases]]
binding = "DATABASE"
database_name = "supermemory-db-preview"
database_id = "b09e126c-8179-4927-876a-6a03ee94334b"

[env.production.ai]
binding = "AI"