name = "dev-cf-ai-backend"
main = "src/index.ts"
compatibility_date = "2024-02-23"
node_compat = true

# tail_consumers = [{service = "new-cf-ai-backend-tail"}]

[[services]]
binding = "THREAD"
service = "tweet-thread"
entrypoint = "ThreadWorker"

# [env.preview]
[[vectorize]]
binding = "VECTORIZE_INDEX"
index_name = "supermem-vector-dev"

# [[vectorize]]
# binding = "VECTORIZE_INDEX"
# index_name = "supermem-vector-prod"

[ai]
binding = "AI"

# [[queues.producers]]
#  queue = "batch-vector-queue"
#  binding = "MY_QUEUE"

#  [[queues.consumers]]
#  queue = "batch-vector-queue"

[[kv_namespaces]]
binding = "KV"
id = "a68a8182f08e46a1b5d11588fdda68dc"
preview_id = "a68a8182f08e46a1b5d11588fdda68dc"

[placement]
mode = "smart"

[[queues.producers]]
  queue = "embedchunks-queue"
  binding ="EMBEDCHUNKS_QUEUE"

[[queues.consumers]]
  queue = "embedchunks-queue"
  max_batch_size = 100
  max_retries = 10
  dead_letter_queue = "embedchunks-dlq"


[[d1_databases]]
binding = "DATABASE"
database_name = "staging-d1-supermemory"
database_id = "40a3bb06-82bd-42f1-aef4-fde04f3635c5"