name = "new-cf-ai-backend"
main = "src/index.ts"
compatibility_date = "2024-02-23"
node_compat = true

# tail_consumers = [{service = "new-cf-ai-backend-tail"}]

[[services]]
binding = "THREAD"
service = "tweet-thread"
entrypoint = "ThreadWorker"

# [env.preview]
[[vectorize]]
binding = "VECTORIZE_INDEX"
index_name = "supermem-vector-dev"

# [[vectorize]]
# binding = "VECTORIZE_INDEX"
# index_name = "supermem-vector-prod"

[ai]
binding = "AI"

# [[queues.producers]]
#  queue = "batch-vector-queue"
#  binding = "MY_QUEUE"

#  [[queues.consumers]]
#  queue = "batch-vector-queue"

[[kv_namespaces]]
binding = "KV"
id = "569c3f2a510943729019f5d1f798e7d9"
preview_id = "569c3f2a510943729019f5d1f798e7d9"

[placement]
mode = "smart"

[[queues.producers]]
  queue = "embedchunks-queue"
  binding ="EMBEDCHUNKS_QUEUE"

[[queues.consumers]]
  queue = "embedchunks-queue"
  max_batch_size = 100
  max_retries = 3
  dead_letter_queue = "embedchunks-dlq"


[[d1_databases]]
binding = "DATABASE"
database_name = "supermemlocal"
database_id = "0f93c990-72fb-489c-8563-57a7bb18dc43"
