name: Build and Deploy Changes

on:
  push:
    branches: [main]
    paths:
      - 'apps/web/**'
      - 'apps/extension/**'
      - 'apps/cf-ai-backend/**'
  pull_request:
    branches: [main]
    paths:
      - 'apps/web/**'
      - 'apps/extension/**'
      - 'apps/cf-ai-backend/**'

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      web_changed: ${{ steps.detect_changes.outputs.web_changed }}
      extension_changed: ${{ steps.detect_changes.outputs.extension_changed }}
      cf_ai_backend_changed: ${{ steps.detect_changes.outputs.cf_ai_backend_changed }}
    steps:
      - uses: actions/checkout@v3
      - name: Fetching all history for all tags and branches
        run: git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
      - name: Detect Changes
        id: detect_changes
        run: |
          WEB_CHANGED="false"
          EXTENSION_CHANGED="false"
          CF_AI_BACKEND_CHANGED="false"
          if [ "${{ github.event_name }}" = "push" ]; then
            DIFF_REF="${{ github.event.before }} ${{ github.sha }}"
          else
            DIFF_REF="${{ github.base_ref }}...${{ github.head_ref }}"
          fi
          if git diff --name-only $DIFF_REF | grep -q 'apps/web/'; then
            WEB_CHANGED="true"
          fi
          if git diff --name-only $DIFF_REF | grep -q 'apps/extension/'; then
            EXTENSION_CHANGED="true"
          fi
          if git diff --name-only $DIFF_REF | grep -q 'apps/cf-ai-backend/'; then
            CF_AI_BACKEND_CHANGED="true"
          fi
          echo "web_changed=$WEB_CHANGED" >> $GITHUB_OUTPUT
          echo "extension_changed=$EXTENSION_CHANGED" >> $GITHUB_OUTPUT
          echo "cf_ai_backend_changed=$CF_AI_BACKEND_CHANGED" >> $GITHUB_OUTPUT
          echo "Differences detected: WEB=$WEB_CHANGED, EXTENSION=$EXTENSION_CHANGED, CF_AI_BACKEND=$CF_AI_BACKEND_CHANGED"
          
  build-extension:
    needs: prepare
    if: needs.prepare.outputs.extension_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/buildextension

  build-app:
    needs: prepare
    if: needs.prepare.outputs.web_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install packages
        run: bun i
        shell: bash

      - name: Build app
        run: bun run pages:build
        working-directory: apps/web
        shell: bash
        env:
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
          BACKEND_SECURITY_KEY: ${{ secrets.BACKEND_SECURITY_KEY }}

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ secrets.CLOUDFLARE_PROJECT_NAME }}
          directory: apps/web/.vercel/output/static
          branch: main

  deploy-cf-worker:
    needs: prepare
    if: needs.prepare.outputs.cf_ai_backend_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@1.2.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          script: wrangler publish
          working-directory: apps/cf-ai-backend
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          SECURITY_KEY: ${{ secrets.BACKEND_SECURITY_KEY }}
